use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_dir = "protos";
    let out_dir = Path::new("src");

    // 1.先删除原有out_dir目录中生成的rs文件
    let _ = fs::remove_dir_all(out_dir);
    let _ = fs::create_dir(out_dir);

    // 创建 lib.rs 文件
    let mod_filename = "lib.rs";
    // let _ = fs::remove_file(&mod_filename); // 可根据实际情况，看是否需要删除
    let mut mod_file = fs::OpenOptions::new()
        .write(true)
        .create(true)
        .open(out_dir.join(mod_filename))?;

    // 2.读取proto_dir目录中所有的proto文件
    // let mut proto_files: Vec<String> = fs::read_dir(proto_dir)?
    //     .filter_map(|e| e.ok())
    //     .map(|e| e.path())
    //     .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("proto"))
    //     .map(|p| p.to_string_lossy().into_owned())
    //     .collect();

    let mut proto_files: Vec<String> = fs::read_dir(proto_dir)?
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("proto"))
        .map(|p| p.to_string_lossy().into_owned())
        .collect();

    proto_files.sort();

    // 3.生成rust代码到out_dir目录中，包含server/client代码生成
    // grpc reflection 描述信息这是一个二进制文件
    // let descriptor_path = out_dir.join("rpc_descriptor.bin"); // 这个功能可选
    tonic_prost_build::configure()
        // .file_descriptor_set_path(&descriptor_path)
        .build_server(true)
        .build_client(true)
        .out_dir(out_dir)
        .compile_protos(&proto_files, &[proto_dir.to_string()])?;

    // 4.将生成的rust模块文件名写入到 mod_file 文件中
    let mut buffer = String::from("// This file is @generated by prost-build. DO NOT EDIT.\n");
    // 先读取所有的rust文件，不包含 mod_file文件
    let mut rs_files: Vec<_> = out_dir
        .read_dir()?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.is_file()
                && p.extension().and_then(|e| e.to_str()) == Some("rs")
                && p.file_name() != Some(OsStr::new(mod_filename))
        })
        .collect();
    rs_files.sort();

    // 将所有文件名对应的模块名字写入buffer
    for path in rs_files {
        if path.file_name() == Some(OsStr::new("google.api.rs")) {
            fs::remove_file(&path)?;
            continue;
        }

        // 获取rust文件对应的模块名字
        let module = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or("invalid filename")?;
        buffer.push_str(&format!("pub mod {};\n", module));

        // 为生成的message实现 serde encode/decode 功能
        let content = fs::read_to_string(&path)?;
        let updated = content.replace(
            "prost::Message",
            "prost::Message, serde::Serialize, serde::Deserialize",
        );

        fs::write(&path, updated)?;
    }

    // 将 buffer 内容一次写入 mod_file 文件中
    // mod_file.write(buffer.as_bytes())?;
    mod_file.write_all(buffer.as_bytes())?;

    Ok(())
}
